// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4905.MecanumTest.subsystems;

import org.usfirst.frc4905.MecanumTest.OI;
import org.usfirst.frc4905.MecanumTest.Robot;
import org.usfirst.frc4905.MecanumTest.RobotMap;
import org.usfirst.frc4905.MecanumTest.commands.*;
import org.usfirst.frc4905.MecanumTest.OI.*;

import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon frontLeft = RobotMap.driveTrainFrontLeft;
    private final CANTalon backRight = RobotMap.driveTrainBackRight;
    private final CANTalon frontRight = RobotMap.driveTrainFrontRight;
    private final CANTalon backLeft = RobotMap.driveTrainBackLeft;
    private final RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new TeleopDrive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
   public void teleopDrive(Joystick driveGamepad){
	   
	   
	   robotDrive.mecanumDrive_Cartesian(OI.getLeftStickVertical(driveGamepad), OI.getLeftStickHorizontal(driveGamepad), OI.getRightStickHorizontal(driveGamepad), 0);//that 0 is a placeholder for a gyro reading
	   
   }
   public void stop(){
	   frontLeft.set(0);
	   frontRight.set(0);
	   backLeft.set(0);
	   backRight.set(0);
   }
    
}

